/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MotorGrafico */

#ifndef _Included_main_MotorGrafico
#define _Included_main_MotorGrafico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_MotorGrafico
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    validateMazeFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_main_MotorGrafico_validateMazeFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     main_MotorGrafico
 * Method:    initFromFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_initFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     main_MotorGrafico
 * Method:    generateNewMaze
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_generateNewMaze
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    setAlgorithm
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setAlgorithm
  (JNIEnv *, jobject, jint);

/*
 * Class:     main_MotorGrafico
 * Method:    resetAnimation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_resetAnimation
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    setAnimationSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setAnimationSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     main_MotorGrafico
 * Method:    setCamera
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setCamera
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     main_MotorGrafico
 * Method:    saveMaze
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_saveMaze
  (JNIEnv *, jobject, jstring);

/*
 * Class:     main_MotorGrafico
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     main_MotorGrafico
 * Method:    setPaused
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_setPaused
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     main_MotorGrafico
 * Method:    stepBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_MotorGrafico_stepBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
